steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/imgwebapp:v1", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/imgwebapp:v1"]
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo 'Docker Container Built'
        ls -la
        ls -al saved_model/
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=k8s/
      - --location=us-west1-b
      - --cluster=project-cluster