apiVersion: app/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp-imageclassifier
  template:
    metadata:
      labels:
        app: myapp-imageclassifier
    spec:
      containers:
      - name: myapp-imageclassifier
        image: gcr.io/venkatareddyjillela-project/imgwebapp:v1
        ports:
        - containerPort: 80